### ISSUE TITLE
require 'activerecord' and 'activesupport'

### ISSUE THREAD

**Issue by IvanUkhov** [nkallen/cache-money#12]
Please replace those requirements with 'active_record' and 'active_support'. They are deprecated from Rails 2.3.5.

**Comment by smtlaissezfaire** [comment]
Fixed on this branch:

http://github.com/smtlaissezfaire/cache-money/tree/fix_test_suite

I've sent a pull request.

**Comment by jamiew** [comment]
Are all these pull requests going anywhere? :x

It'd be great to point people at repositories that are actually being maintained, since this is an awesome library.
