### ISSUE TITLE
Rails fails when memcached is down

### ISSUE THREAD

**Issue by IvanUkhov** [nkallen/cache-money#13]
Is it possible to avoid caching if memcached is down without raising an error?

**Comment by smtlaissezfaire** [comment]
Here's how I did it (the initializer code):

http://gist.github.com/284440

This ticket should be closed

**Comment by PatrickTulskie** [comment]
That doesn't solve the issue of memcached going down when it's serving requests.  Still need something to rescue no server errors mid-run unless you are constantly reloading your memcache connection every time.
