### ISSUE TITLE
Documentation fix for gem usage

### ISSUE THREAD

**Issue by paulbjensen** [nkallen/cache-money#16]
I just tried to use the gem as described in the docs, and I got this error:

`load_missing_constant': uninitialized constant MemCache (NameError)

I added the memcache-client rubygem as a gem dependency in my rails app's environment.rb file:

```
config.gem 'memcache-client',     :source => 'http://gemcutter.org', :lib => "memcache"
```

and modified the config/initializers/cache_money.rb file like so:

```
1: require 'cache_money'
2: require 'memcache'
```

This fixed that issue. Could someone update the docs?

**Comment by baron** [comment]
thanks for this info.  Would be nice to update this and gem specs as well.

**Comment by paulbjensen** [comment]
Closing as this is an old issue.
