### ISSUE TITLE
config/memcached.yaml - namespace isn't honored

### ISSUE THREAD

**Issue by dkindlund** [nkallen/cache-money#2]
the master and libmemcached branches do not use the 'namespace' supplied in memcached.yml

**Comment by dkindlund** [comment]
apparently, this issue is solved by setting a "prefix_key" in memcached.yml

**Comment by schubert** [comment]
I think that may only work if you are using the memcached client not the memcache-client either way something needs to be documented or fixed because namespace is not being honored. that this not very usable in multiple-environment apps with a single memcache.
